package com.iscms.web;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import java.io.IOException;
import java.io.PrintWriter;

// First servlet — proves the web layer works end-to-end.
// URL: http://localhost:8080/iscms/hello
@WebServlet("/hello")
public class HelloServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp)
            throws ServletException, IOException {

        resp.setContentType("text/html; charset=UTF-8");
        PrintWriter out = resp.getWriter();

        out.println("<!DOCTYPE html>");
        out.println("<html><head><title>Hello — ISC-MS</title></head><body>");
        out.println("<h1>Hello, ISC-MS Web!</h1>");
        out.println("<p>This page was generated by a Java Servlet at "
                + new java.util.Date() + ".</p>");
        out.println("<p><a href='index.html'>Back to home</a></p>");
        out.println("</body></html>");
    }
}