package com.iscms.dao;

import com.iscms.model.Installment;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

// DAO interface for installment records — supports CRUD operations,
// status updates, and queries for overdue detection.
public interface InstallmentDAO {

    // Inserts a single installment row. installment_id is auto-generated by DB.
    void insert(Installment installment);

    // Bulk insert helper — used when creating the 12-month schedule on membership activation
    void insertAll(List<Installment> installments);

    // Returns all installments for a given membership, ordered by installment_no
    List<Installment> findByMembershipId(int membershipId);

    // Returns all installments for a given member, ordered by due_date
    List<Installment> findByMemberId(int memberId);

    // Returns one installment by ID
    Optional<Installment> findById(int installmentId);

    // Returns active (PENDING + OVERDUE) installments past their due date for a member.
    // Used by login-trigger to surface overdue installments before allowing other actions.
    List<Installment> findOverdueForMember(int memberId);

    // Marks an installment as PAID with a payment_id linking the cleared payment record
    void markPaid(int installmentId, int paymentId);

    // Updates the status of all PENDING installments past their due_date to OVERDUE.
    // Called periodically (login-trigger pattern) — returns the number of rows updated.
    int markOverdueGlobal();

    // Counts installments still owed (PENDING + OVERDUE) for a membership.
    // Used to determine whether a membership has any open balance.
    int countUnpaidByMembership(int membershipId);
}